name: Build and Push Docker Image

on:
  push:
    branches: [main]

permissions:
  contents: write    # Allow the action to write to the repository
  packages: write    # Allow the action to push Docker images to GitHub Container Registry
  id-token: read     # Allow the action to read ID tokens (if necessary)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project
        run: mvn clean install

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_LOWER:latest .
          docker push ghcr.io/$REPO_LOWER:latest





